version: "3.9"

services:
  ktvilla-api:
    image: surfacestay_api
    networks:
      - hosting
    command: >
      sh -c "yarn rw prisma migrate deploy &&
             yarn rw serve api"
    env_file:
      - .env.prod
    environment:
      - LETSENCRYPT_HOST=api.kt-villa.com
      - VIRTUAL_HOST=api.kt-villa.com
      - VIRTUAL_PORT=8911

networks:
  hosting:
    name: hosting
    external: true
