version: "3.9"

services:
  ktvilla:
    image: surfacestay
    networks:
      - hosting
    expose:
      - "8910"
    command: >
      sh -c "yarn rw prisma migrate deploy &&
             yarn rw serve"
    env_file:
      - .env.prod
    environment:
      - LETSENCRYPT_HOST=www.kt-villa.com
      - VIRTUAL_HOST=www.kt-villa.com
      - VIRTUAL_PORT=8910

networks:
  hosting:
    name: hosting
    external: true
